# === TIER 0: WAREHOUSE GATEWAY ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: warehouse-gateway
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  health:
    analyses: []
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
# === TIER 1: DEV ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-eus-core
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - warehouse-gateway
  health:
    analyses: []
  promotionTemplate:
    vars:
    - name: repoURL
      value: https://github.com/lerma-org/kargo-simple.git
    - name: branch
      value: main
    spec:
      steps:
      - task:
          name: promote

---
# === TIER 1.5: STAGE GATEWAY (Fan-out point) ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-gateway
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: orange
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev-eus-core
  health:
    analyses: []
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
# === TIER 2: STAGE (6 parallel stages) ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-eus-core
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - stage-gateway
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-eus-nrt
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - stage-gateway
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-eus-usaf
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - stage-gateway
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-local-aio1
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - stage-gateway
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-local-lab
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - stage-gateway
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-local-qatar
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - stage-gateway
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
# === TIER 3: TEST ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test-eus-core
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - stage-eus-core
      - stage-eus-nrt
      - stage-eus-usaf
      - stage-local-aio1
      - stage-local-lab
      - stage-local-qatar
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: false
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
# === TIER 4: UAT ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat-eus-core
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: cyan
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - test-eus-core
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
# === TIER 5: PROD GATE (Manual approval point) ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: promote-to-prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - test-eus-core
      - uat-eus-core
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: false
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
# === TIER 6: PROD (16 parallel stages) ===
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-core
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-acad
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-acn
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-cpc
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-cummins
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-eydemo
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-lennar
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-mon
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-msft
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-mtus
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-nrt
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-sdrl
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-slalom
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eus-vrt
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-local-qatar
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-scus-wer
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - promote-to-prod
  health:
    analyses: []
  promotion:
    autoPromotionEnabled: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: openpr
          value: "true"
